sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master/docs
    local_dir: docs
    repo: rudy.org.cn
    fqdn: rudy.org.cn
    target_branch: master/docs
    email: rudy.architect@foxmail.com
    name: rudyarchitect