language: go
install:
  - go get github.com/gohugoio/hugo 
script:
  - hugo
deploy:
  provider: pages 
  skip-cleanup: true 
  local-dir: docs 
  target-branch: gh-pages 
  github-token: $GITHUB_TOKEN 
  fqdn:  rudy.org.cn 
  keep-history: true 
  on:
    branch: master 
    