publishDir = "docs"
baseURL = "https://rudy.org.cn/"
title = "Rudy's blog" 
languageCode = "zh-cn" 
hasCJKLanguage = true 
theme = "LeaveIt" 
paginate = 11 
enableEmoji = true 
enableRobotsTXT = true 
googleAnalytics = "" 
preserveTaxonomyNames = true
[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true
[Permalinks]
 posts = "/:year/:filename/"
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
[params]
    since = 2019
    author = "Rudy"
    avatar = "" 
    subtitle = ""
    cdn_url = "" 
    home_mode = "" 
    enableGitalk = true 
    google_verification = ""
    description = "" 
    keywords = "" 
    beian = ""
    baiduAnalytics = ""
    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
[params.social]
    GitHub = ""
    Twitter = ""
    Email   = ""
    Instagram = ""
    Wechat = ""  
    Facebook = ""
    Telegram = ""
    Dribbble = ""
    Medium = ""
[params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientID = ""
    clientSecret = ""
    repo = "" 
    owner = "" 
    admin= "" 
    id= "location.pathname" 
    labels= "gitalk" 
    perPage= 15 
    pagerDirection= "last" 
    createIssueManually= false
    distractionFreeMode= false 